server:
  port: 8080

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

security:
  public-routes:
    - /api/auth/login
    - /api/auth/register
spring:
  application:
    name: api-gateway
  main:
    web-application-type: servlet